// <auto-generated />
using System;
using BlueReef.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlueReef.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20210710053501_sendemail")]
    partial class sendemail
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlueReef.Models.Registraion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoginId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Rememberme")
                        .HasColumnType("bit");

                    b.Property<int?>("RoleManagementId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleManagementId");

                    b.ToTable("Registraions");
                });

            modelBuilder.Entity("BlueReef.Models.RoleManagement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoleManagements");
                });

            modelBuilder.Entity("BlueReef.Models.SendEmail", b =>
                {
                    b.Property<int>("SendemailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SendemailID");

                    b.ToTable("sendEmails");
                });

            modelBuilder.Entity("BlueReef.Models.Registraion", b =>
                {
                    b.HasOne("BlueReef.Models.RoleManagement", "RoleManagement")
                        .WithMany()
                        .HasForeignKey("RoleManagementId");

                    b.Navigation("RoleManagement");
                });
#pragma warning restore 612, 618
        }
    }
}
